
app = 'full-stack-open-pokedex-autumn-darkness-5509'
primary_region = 'bom'

[env]
  PORT = "5000"
  
[processes]
  app = "node app.js"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[deploy]
  strategy = "canary"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
