# fly.toml app configuration file generated for full-stack-open-pokedex-autumn-darkness-5509 on 2025-01-21T21:46:26+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-autumn-darkness-5509'
primary_region = 'bom'

[env]
  PORT = "5000"
  
[processes]
  app = "node app.js"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
